import MarketingEvent from "../../models/marketingEvent.js";
import { generateForEntity } from "./generator.js";

/**
 * ERP → Marketing AI event bus (Phase 1).
 * Any ERP create hook calls emitMarketingTrigger fire-and-forget. The event is
 * deduplicated by (schoolId|trigger|entityId) so replays never double-generate.
 * Auto-suggestion is OFF unless MARKETING_AUTO_SUGGEST=true (protects AI cost
 * during rollout); the Suggestions screen can still generate manually.
 */
export const emitMarketingTrigger = async ({
  schoolId,
  entityType,
  entityId,
  trigger,
  entitySummary = "",
  actor = "system",
}) => {
  const dedupeKey = [String(schoolId), trigger, String(entityId)].join("|");

  let eventRecord = await MarketingEvent.findOne({ dedupeKey }).lean();
  if (eventRecord) {
    return { created: false, event: eventRecord };
  }

  eventRecord = await MarketingEvent.create({
    schoolId,
    trigger,
    entityType,
    entityId: String(entityId),
    entitySummary,
    dedupeKey,
  });

  if (process.env.MARKETING_AUTO_SUGGEST !== "true") {
    return { created: true, event: eventRecord, autoGenerated: false };
  }

  processEvent(eventRecord._id).catch((err) =>
    console.error("marketing trigger failed:", err.message),
  );
  return { created: true, event: eventRecord, autoGenerated: true };
};

/** Generate drafts for all channels for this pending trigger event. */
export const processEvent = async (eventId) => {
  const evt = await MarketingEvent.findById(eventId);
  if (!evt) return;
  try {
    const posts = await generateForEntity({
      schoolId: evt.schoolId,
      entityType: evt.entityType,
      entityId: evt.entityId,
      trigger: evt.trigger,
      actor: "auto-trigger",
    });
    const okPosts = posts.filter((p) => p && p._id);
    evt.generatedPostIds = okPosts.map((p) => p._id);
    evt.status = "processed";
    evt.lastError = undefined;
    await evt.save();
  } catch (err) {
    evt.status = "failed";
    evt.attempts = (evt.attempts || 0) + 1;
    evt.lastError = err.message;
    await evt.save();
  }
  return evt;
};